FROM node:16

WORKDIR /

COPY . /

# build dependencies
RUN cd core && \
  npm install && \
  npm run build && \
  cd ../relay && \
  npm install && \
  npm run build


ENTRYPOINT [ "/usr/local/bin/node", "/relay/build/src/app.js" ]
