FROM node:16

WORKDIR /

COPY . /

# build dependencies
RUN cd core && \
  npm install && \
  npm run build && \
  cd ../baker-endpoint && \
  npm install && \
  npm run build

ENTRYPOINT [ "/usr/local/bin/node", "/baker-endpoint/build/src/app.js" ]
