apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flashbake-flywheel.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
data:
  FLYWHEEL_SK: {{ .Values.secrets.flywheel_sk | b64enc  }}
