apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flashbake-endpoint.fullname" . }}
  labels:
    {{- include "flashbake-endpoint.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flashbake-endpoint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flashbake-endpoint.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flashbake-endpoint.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: relay
              containerPort: {{ .Values.relay_listener_port }}
              protocol: TCP
            - name: baker
              containerPort: {{ .Values.baker_listener_port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
          - run
          - --relay_listener_port
          - "{{ .Values.relay_listener_port }}"
          - --tezos_rpc_url
          - {{ .Values.tezos_rpc_url }}
          - --baker_listener_port
          - "{{ .Values.baker_listener_port }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
