apiVersion: v1
kind: Service
metadata:
  name: {{ include "flashbake-endpoint.fullname" . }}
  labels:
    {{- include "flashbake-endpoint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.relay_listener_port }}
      targetPort: {{ .Values.relay_listener_port }}
      protocol: TCP
      name: relay-listener
    - port: {{ .Values.baker_listener_port }}
      targetPort: {{ .Values.baker_listener_port }}
      protocol: TCP
      name: baker-listener
  selector:
    {{- include "flashbake-endpoint.selectorLabels" . | nindent 4 }}
