name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: "Install Dependencies"
      run: |
        sudo apt-get update && sudo apt-get install build-essential git libusb-1.0-0 libusb-1.0-0-dev libudev-dev
    - name: "Build and lint deploy scripts"
      run: |
        cd core
        npm i
        npm run build
        cd ../relay
        npm i
        npm run build
        cd ../baker-endpoint
        npm i
        npm run build
  publish_to_npm:
    runs-on: ubuntu-latest
    needs: [build_all]
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Get Release Version
        id: get_release_version
        run: echo "::set-output name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}"

      - run: |
          set -x

          RELEASE_VERSION=$(echo ${{ steps.get_release_version.outputs.RELEASE_VERSION }} | sed -e s/v//)
          cd core
          npm i
          npm version  $RELEASE_VERSION
          npm run build
          npm publish
          cd ../relay
          npm i
          npm version  $RELEASE_VERSION
          npm run build
          npm publish
          cd ../baker-endpoint
          npm i
          npm version  $RELEASE_VERSION
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
